### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by WeltensiedlerDE** [DarkShadow44/SereneSeasons#13]
### What's the issue you encountered?

Using Forge 10.13.4.1614 for MC 1.7.10 and Serene Seasons for 1.7.10 - Version 1.2.18 crashing on startup.</br>

### How can the issue be reproduced?

I'm only using forge-1.7.10-10.13.4.1614-1.7.10-universal.jar and SereneSeasons-1.7.10-1.2.18.jar as the only one mod.</br>

I'm using a linux server running Ubuntu and Java OpenJDK 1.8.0_242.</br>

### Logs
[Crash Log](https://pastebin.com/jHKSCgWq)
</br>

### Mod Version
SereneSeasons-1.7.10-1.2.18.jar and also compiled SereneSeasons-1.7.10-1.2.19.jar</br>

**Comment by WeltensiedlerDE** [comment]
Stll not working

**Comment by DarkShadow44** [comment]
Can you please provide a full log?
Also, how did you setup your server? Simple instructions to reproduce would be helpful.

**Comment by WeltensiedlerDE** [comment]
This is the log the error occured:

[13:50:40] [Server thread/INFO]: Starting minecraft server version 1.7.10
[13:50:42] [Server thread/INFO]: Loading properties
[13:50:42] [Server thread/INFO]: Default game type: SURVIVAL
[13:50:42] [Server thread/INFO]: Generating keypair
[13:50:42] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:50:42] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/world/biome/BiomeGenBase
	at net.minecraftforge.common.BiomeDictionary.<clinit>(BiomeDictionary.java:113) ~[BiomeDictionary.class:?]
	at net.minecraftforge.common.ForgeModContainer.postInit(ForgeModContainer.java:290) ~[ForgeModContainer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) ~[Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.biome.BiomeGenBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 29 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:622) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 29 more
Caused by: java.lang.NullPointerException
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:641) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:247) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:226) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1124) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:247) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:332) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:835) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:805) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:610) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:184) ~[SereneSeasons-1.7.10-1.2.18.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 29 more
[13:50:42] [Server thread/ERROR]: This crash report has been saved to: /home/cludos/./crash-reports/crash-2020-02-28_13.50.42-server.txt

**Comment by WeltensiedlerDE** [comment]
And to reproduce just start a clean installed server with forge 1614 for 1.7.10 and put SereneSeason as the only mod in the mod-folder.

And this occured on startup.

**Comment by DarkShadow44** [comment]
Works fine for me with the latest git version. Your server is installed from forge-1.7.10-10.13.4.1614-1.7.10-installer.jar ?

**Comment by WeltensiedlerDE** [comment]
Hmm, thats curious. I will give it a second try and will give you feedback, tommorow I think. And yes, this is the forge installer I used.

**Comment by WeltensiedlerDE** [comment]
Hmm, I'm sure I have build it before. But if I build it now, I get a version vor 1.12.

These steps I'm doing:

git clone https://github.com/DarkShadow44/SereneSeasons.git
gradle build

What am I doing wrong?

Sorry for my incompetence. I'm not building so often on linux.

**Comment by DarkShadow44** [comment]
You have to checkout the branch "1.7.10_backport"

**Comment by WeltensiedlerDE** [comment]
So, next try. This time with other mods, but no worldgen or biomes modifikation. And with use of compiled SereneSeasons-1.7.10-1.2.19.jar.

**latest.log**
`[21:28:02] [Server thread/INFO]: Starting minecraft server version 1.7.10
[21:28:46] [Server thread/INFO]: Loading properties
[21:28:46] [Server thread/INFO]: Default game type: SURVIVAL
[21:28:46] [Server thread/INFO]: Generating keypair
[21:28:46] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:29:02] [Server thread/INFO]: Preparing level "world"
[21:29:37] [Thread-14/INFO]: Starting backup of dim -37...
[21:29:37] [Thread-14/INFO]: Backup finished
[21:29:51] [Thread-15/INFO]: Starting backup of dim -38...
[21:29:51] [Thread-15/INFO]: Backup finished
[21:29:59] [Thread-16/INFO]: Starting backup of dim -17...
[21:29:59] [Thread-16/INFO]: Backup finished
[21:30:13] [Thread-17/INFO]: Starting backup of dim -39...
[21:30:13] [Thread-17/INFO]: Backup finished
[21:30:39] [Thread-18/INFO]: Starting backup of dim 1...
[21:30:39] [Thread-18/INFO]: Backup finished
[21:30:59] [Thread-19/INFO]: Starting backup of dim -1...
[21:30:59] [Thread-19/INFO]: Backup finished
[21:30:59] [Thread-20/INFO]: Starting backup of dim 0...
[21:30:59] [Server thread/INFO]: Preparing start region for level 0
[21:31:00] [Server thread/INFO]: Preparing spawn area: 93%
[21:31:00] [Server thread/INFO]: Done (125,849s)! For help, type "help" or "?"
[21:31:03] [Thread-20/INFO]: Backup finished
[21:31:08] [Thread-21/INFO]: Starting backup of dim 10...
[21:31:09] [Thread-21/INFO]: Backup finished
[21:31:10] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: net.minecraft.world.biome.BiomeGenHills cannot be cast to sereneseasons.asm.IBiomeMixin
	at sereneseasons.season.SeasonASMHelper.getFloatTemperature(SeasonASMHelper.java:192) ~[SeasonASMHelper.class:?]
	at sereneseasons.season.SeasonASMHelper.getFloatTemperature(SeasonASMHelper.java:186) ~[SeasonASMHelper.class:?]
	at sereneseasons.handler.season.RandomUpdateHandler.onWorldTick(RandomUpdateHandler.java:136) ~[RandomUpdateHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_381_RandomUpdateHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[21:31:10] [Server thread/ERROR]: This crash report has been saved to: /home/cludos/./crash-reports/crash-2020-03-03_21.31.10-server.txt
[21:31:10] [Server thread/INFO]: Stopping server
[21:31:10] [Server thread/INFO]: Saving players
[21:31:10] [Server thread/INFO]: Saving worlds
[21:31:10] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[21:31:10] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[21:31:10] [Server thread/INFO]: Saving chunks for level 'world'/The End
[21:31:10] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[21:31:11] [Server thread/INFO]: Saving chunks for level 'world'/Spirit World
[21:31:11] [Server thread/INFO]: Saving chunks for level 'world'/Torment
[21:31:11] [Server thread/INFO]: Saving chunks for level 'world'/Mirror
[21:31:11] [Server thread/INFO]: Saving chunks for level 'world'/Wyvern Lair
[21:31:11] [Thread-29/INFO]: Starting backup of dim 0...
`

**crash-2020-03-03_21.31.10-server.txt**
`---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 03.03.20 21:31
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.biome.BiomeGenHills cannot be cast to sereneseasons.asm.IBiomeMixin
	at sereneseasons.season.SeasonASMHelper.getFloatTemperature(SeasonASMHelper.java:192)
	at sereneseasons.season.SeasonASMHelper.getFloatTemperature(SeasonASMHelper.java:186)
	at sereneseasons.handler.season.RandomUpdateHandler.onWorldTick(RandomUpdateHandler.java:136)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_381_RandomUpdateHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.15.0
	Java Version: 1.8.0_242, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1057089752 bytes (1008 MB) / 3379560448 bytes (3223 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 1 total; -Xmx8G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	movillages{1.4.2} [Mo' Villages] ([1.7.10]MoVillages-1.4.2.jar) 
	UCHIJAAAA	deconstruction{3.0.2} [Deconstruction Table] ([MC1.7.10]DeconTable-3.0.2.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJAAAA	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) 
	UCHIJAAAA	astikoor{1.0.0} [Astikoor] (astikoor-1.7.10-1.0.0.jar) 
	UCHIJAAAA	baublesstuff{2.1.2} [Baubles Stuff] (baublesstuff-2.1.2.jar) 
	UCHIJAAAA	betterquesting{3.0.322} [Better Questing] (BetterQuesting-3.0.322.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJAAAA	bookshelf{1.0.4.172} [Bookshelf] (Bookshelf-1.7.10-1.0.4.172.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.2} [Carpenter's Blocks] (Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar) 
	UCHIJAAAA	ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	cookingbook{1.0.140} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.140.jar) 
	UCHIJAAAA	MineTweaker3{3.1.0} [MineTweaker 3] (CraftTweaker-1.7.10-3.1.0-legacy.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	ForgeEssentials{1.4.6} [Forge Essentials] (forgeessentials-1.7.10-1.4.6.1357-server.jar) 
	UCHIJAAAA	gravestone{0.7.10.3} [Gravestone] (GraveStone Mod 0.7.10.3.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	mo{@VERSION@} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.4.jar) 
	UCHIJAAAA	mcmmo{1.0} [MCMMO - Forge] (mcmmo-1.3.1.jar) 
	UCHIJAAAA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	bq_npc_integration{@VERSION@} [NPC Integration] (NPCIntegration-3.0.30.jar) 
	UCHIJAAAA	oretweaker{1.0.2} [Ore Tweaker] (OreTweaker-1.0.2-1.7.10.jar) 
	UCHIJAAAA	bonecraft{1.7.2b} [Pam's BoneCraft] (Pam's BoneCraft 1.7.2b.zip) 
	UCHIJAAAA	desertcraft{1.7.2b} [Pam's DesertCraft] (Pam's DesertCraft 1.7.10a.zip) 
	UCHIJAAAA	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	simplerecipes{1.7.10a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.7.10a.jar) 
	UCHIJAAAA	weeeflowers{1.7.2b} [Pam's Weee! Flowers] (Pam's WeeeFlowers 1.7.2b.zip) 
	UCHIJAAAA	permissionforge{1.7.10-1.0.4-beta} [PermissionForge] (PermissionForge-1.7.10-1.0.4.jar) 
	UCHIJAAAA	permissionex{2.0} [PermissionEx] (PermissionForge-1.7.10-1.0.4.jar) 
	UCHIJAAAA	row{1.7.10-5.8-RC7} [Rails of War] (RailsOfWar-1.7.10-5.8-RC7.jar) 
	UCHIJAAAA	rowam{9.0.1} [Rails of War Automation Module] (ROWAM-1.7.10-9.0.1.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	UCHIJAAAA	sereneseasons{1.2.19} [Serene Seasons] (SereneSeasons-1.7.10-1.2.19.jar) 
	UCHIJAAAA	signpost{1.06.1} [Sign Post] (signpost-1.7.10-1.06.1.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.11} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.11.jar) 
	UCHIJAAAA	bq_standard{3.0.174} [Standard Expansion] (StandardExpansion-3.0.174.jar) 
	UCHIJAAAA	tc{4.4.1_021} [Traincraft] (Traincraft-4.4.1_021.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJAAAA	totemic{1.7.10-0.6.2} [Totemic] (Totemic-1.7.10-0.6.2.jar) 
	UCHIJAAAA	TSteelworks{1.7.10-1.1.2} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.2-20.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHIJAAAA	wallpaper{0.9} [Wallpaper] (wallpaper-0.9-1.7.10.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	witcherypatch{1.0.0} [WitcheryPatch] (WitcheryPatch-1.7.10-1.0.0.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	ZDoctorBB{1.2} [Blood Baubles] (ZDoctorBB-1.7.10-Server.jar) 
	UCHIJAAAA	HungerOverhaul{1.7.10-1.0.0.jenkins104} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jenkins104.jar) 
	ForgeEssentials: Running ForgeEssentials 1.4.6.1357 (c6f97c1). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from MatterOverdrive-1.7.10-0.4.4.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by WeltensiedlerDE** [comment]
For better reading:

[latest.log](https://pastebin.com/SDdRHuW5)
[crash-2020-03-03_21.31.10-server.txt](https://pastebin.com/zkyhWMhV)

**Comment by DarkShadow44** [comment]
Could be an incompatibility with another mods. Can you try only forge and SereneSeasons?

**Comment by DarkShadow44** [comment]
Any news on this? This is too many mods for me to test.
