### ISSUE TITLE
The Seasons Clock causes a crash.

### ISSUE THREAD

**Issue by HRudyPlayZ** [DarkShadow44/SereneSeasons#20]
The seasons clock seems to cause a client crash when rendered on a specific season.

Here is the log:

`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/31/20 9:36 PM
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 64
	at sereneseasons.item.ItemSeasonClock.getIcon(ItemSeasonClock.java:59)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:484)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:271)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at sereneseasons.item.ItemSeasonClock.getIcon(ItemSeasonClock.java:59)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:484)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: sereneseasons.item.ItemSeasonClock@5aaa54c7
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:271)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (402, 250). Absolute: (805, 377)
	Screen size: Scaled: (800, 439). Absolute: (1600, 877). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['HRudyPlayZ'/213, l='MpServer', x=230.22, y=76.62, z=-177.81]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (256,64,-48), Chunk: (at 0,4,0 in 16,-3; contains blocks 256,0,-48 to 271,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1401851 game time, 966370 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityCreeper['Creeper'/520, l='MpServer', x=157.50, y=24.00, z=-254.50], MoCEntityGoat['Goat'/137, l='MpServer', x=345.28, y=75.00, z=-214.28], MoCEntityMaggot['Maggot'/152, l='MpServer', x=358.75, y=65.00, z=-58.78], MoCEntityWerewolf['Werewolf'/410, l='MpServer', x=226.50, y=30.00, z=-293.50], MoCEntityWerewolf['Werewolf'/411, l='MpServer', x=228.22, y=30.00, z=-292.22], MoCEntityWerewolf['Werewolf'/412, l='MpServer', x=229.81, y=30.00, z=-293.81], MoCEntitySnake['Snake'/30, l='MpServer', x=143.72, y=70.44, z=-79.28], EntityCreeper['Creeper'/432, l='MpServer', x=160.50, y=34.00, z=-115.50], EntityHorse['Horse'/59, l='MpServer', x=195.72, y=73.00, z=-193.13], EntityHorse['Horse'/60, l='MpServer', x=207.28, y=68.00, z=-190.25], MoCEntityBee['Bee'/61, l='MpServer', x=198.88, y=70.00, z=-141.41], EntityPlayerDummy['entity.rfpr.PlayerDummy.name'/317, l='MpServer', x=230.22, y=74.82, z=-177.81], EntityCreeper['Creeper'/579, l='MpServer', x=283.50, y=12.00, z=-222.50], EntityHorse['Horse'/72, l='MpServer', x=231.00, y=71.00, z=-210.91], MoCEntityAnt['Ant'/73, l='MpServer', x=207.45, y=71.00, z=-201.80], MoCEntityFox['Fox'/82, l='MpServer', x=242.75, y=69.00, z=-213.16], EntityZombie['Zombie'/83, l='MpServer', x=243.34, y=51.00, z=-186.31], EntityZombie['Zombie'/84, l='MpServer', x=240.28, y=55.00, z=-181.84], MoCEntityFirefly['Firefly'/85, l='MpServer', x=248.24, y=75.00, z=-149.21], EntityClientPlayerMP['HRudyPlayZ'/213, l='MpServer', x=230.22, y=76.62, z=-177.81], MoCEntityAnt['Ant'/215, l='MpServer', x=267.59, y=64.00, z=-244.44], MoCEntityCricket['Cricket'/216, l='MpServer', x=292.34, y=64.00, z=-239.53], MoCEntityButterfly['ButterFly'/90, l='MpServer', x=251.20, y=69.00, z=-169.49], MoCEntityCricket['Cricket'/219, l='MpServer', x=255.25, y=63.00, z=-267.88], EntityZombie['Zombie'/92, l='MpServer', x=262.47, y=21.00, z=-125.56], MoCEntityFox['Fox'/221, l='MpServer', x=300.25, y=63.00, z=-264.75], EntitySkeleton['Skeleton'/93, l='MpServer', x=257.50, y=33.00, z=-128.50], EntityCreeper['Creeper'/94, l='MpServer', x=266.50, y=24.00, z=-100.50], EntityCreeper['Creeper'/95, l='MpServer', x=267.66, y=25.00, z=-102.00], EntityPig['Pig'/98, l='MpServer', x=272.41, y=71.00, z=-235.06], EntityZombie['Zombie'/610, l='MpServer', x=165.50, y=23.00, z=-232.50], MoCEntitySnake['Snake'/227, l='MpServer', x=301.28, y=64.00, z=-293.94], MoCEntitySnake['Snake'/228, l='MpServer', x=316.63, y=69.00, z=-293.41], MoCEntityAnt['Ant'/100, l='MpServer', x=279.91, y=65.00, z=-201.88], MoCEntityBird['Bird'/233, l='MpServer', x=329.22, y=69.00, z=-260.78], MoCEntityFox['Fox'/107, l='MpServer', x=297.53, y=65.00, z=-204.47], MoCEntityBee['Bee'/108, l='MpServer', x=288.34, y=67.00, z=-190.03], MoCEntityWerewolf['Werewolf'/109, l='MpServer', x=291.19, y=29.00, z=-181.84], MoCEntityEnt['Ent'/111, l='MpServer', x=295.28, y=66.00, z=-68.72], MoCEntityFox['Fox'/241, l='MpServer', x=159.84, y=72.00, z=-297.69], MoCEntityBee['Bee'/127, l='MpServer', x=333.59, y=77.00, z=-122.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 414567936 bytes (395 MB) / 1419247616 bytes (1353 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	futurecommands{1.3} [Future Commands] ([1.7.10] Future Commands.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJAAAA	advancedhud{0.1.14} [Advanced HUD] (AdvancedHUD-1.7.10-0.1.14.jar) 
	UCHIJAAAA	asmc{1.0.2} [§dASMC] (ASMC-1.7.10-1.0.2.jar) 
	UCHIJAAAA	hud{1.3.5} [Better HUD] (Better HUD by NukeDuck [1.7.10][1.3.5].jar) 
	UCHIJAAAA	betterbeginnings{0.9.6-R1a} [BetterBeginnings] (betterbeginnings-MC1.7.10-b0.9.6-R2a.jar) 
	UCHIJAAAA	cacti{1.0.1} [Cacti] (cacti-1.0.1-1.7.10.jar) 
	UCHIJAAAA	campfirebackport{${version}} [Campfire Backport] (campfirebackport-1.7.10-1.6.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	chococraft{4.3.1} [§eChocoCraft Plus] (ChocoCraftPlus-1.7.10-4.3.1.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.7.10-v6b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v6b.jar) 
	UCHIJAAAA	DescriptionTags{1.0} [Description Tags] (DescriptionTags-1.0-1.7.10.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAA	emojicord{1.1.1.39} [Emojicord] (Emojicord-1.7.10-1.1.1.39-universal.jar) 
	UCHIJAAAA	enviromine{1.3.124} [EnviroMine] (EnviroMine-1.3.124.jar) 
	UCHIJAAAA	etfuturum{@VERSION@} [Et Futurum] (Et.Futurum-1.7.3-K.jar) 
	UCHIJAAAA	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	UCHIJAAAA	hudwidgets{0.6.1} [HUDWidgets] (HUDWidgets_[1.7.10]-0.6.1.jar) 
	UCHIJAAAA	kleeslabs{1.0} [KleeSlabs] (kleeslabs-mc1.7.10-1.2.9.jar) 
	UCHIJAAAA	netheriteplus{0.9 Beta} [NetheritePlus+] (NetheritePlus_1.7.10_Beta0.9.jar) 
	UCHIJAAAA	notenoughcats{2.1.0} [§eNot Enough Pets] (NotEnoughPets-1.7.10-v2.1.0.jar) 
	UCHIJAAAA	Progression{0.4.1} [Progression] (Progression-1.7.10-0.4.1.jar) 
	UCHIJAAAA	rfpr{8.1.0} [Real First-Person Render] (Real First-Person Render-1.7.10-8.1.1.jar) 
	UCHIJAAAA	sereneseasons{1.2.18} [Serene Seasons] (SereneSeasons-1.7.10-1.2.18.jar) 
	UCHIJAAAA	skinport{1.7.10-v10c} [SkinPort] (SkinPort-1.7.10-v10c.jar) 
	UCHIJAAAA	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	Tails{1.7.10-1.4.1a} [Tails] (Tails-1.7.10-1.4.1a.jar) 
	UCHIJAAAA	tidbits{1.7.10-1.2} [Tidbits] (tidbits-1.7.10-1.2.jar) 
	UCHIJAAAA	yumalib{0.0.0} [YumaLib] (UpToDateMod-mc1.7.10-2.3.3.jar) 
	UCHIJAAAA	uptodate{2.3.3} [UpToDateMod] (UpToDateMod-mc1.7.10-2.3.3.jar) 
	UCHIJAAAA	VillageNames{3.3.1} [§6Village Names] (VillageNames-1.7.10-3.3.1.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'AMD Radeon(TM) R7 Graphics'
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) R7 Graphics GL version 4.5.13492 Compatibility Profile Context 22.19.677.257, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)`

**Comment by BikeAndGame** [comment]
Yo hello there, I think I found what happens. When i use the command **/sereneseasons setseason mid_spring** for example and i hold the seasons clock it crashes, BUT when I don't hold the clock it works perfectly so just don't use the clock, It's useless, 
non-functioning and only for decoration purporses. Just remove it from your chest/inventory/itemframes and try it!

**Comment by danielrossyamitrano** [comment]
I found out that version 1.3 at least has this issue already fixed. Should I close it @DarkShadow44?

**Comment by DarkShadow44** [comment]
Yeah, lets close this then. If you have further issues, please open a new ticket and I will fix it soon(ish)!
