### ISSUE TITLE
[Crash] 1.7.10 Crashing because of incorrect cast

### ISSUE THREAD

**Issue by TekuSP** [DarkShadow44/SereneSeasons#24]
```
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.biome.BiomeGenForest cannot be cast to sereneseasons.asm.IBiomeMixin
	at sereneseasons.season.SeasonASMHelper.canBlockFreezeInSeason(SeasonASMHelper.java:91)
	at sereneseasons.handler.season.SeasonHandler.onPopulateChunk(SeasonHandler.java:128)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_406_SeasonHandler_onPopulateChunk_Populate.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.terraingen.TerrainGen.populate(TerrainGen.java:36)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:429)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Running on Windows 10 (Build 19042.906 20H2)
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)

**Comment by TekuSP** [comment]
[latest.log](https://github.com/DarkShadow44/SereneSeasons/files/6310638/latest.log)
I am providing log and looking into bug myself, if I have resolution, I will fork and make Pull Request for you to review.

**Comment by TekuSP** [comment]
```
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:138]: Biome is not instance of an IBiomeMixin!
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:139]: Biome is: net.minecraft.world.biome.BiomeGenTaiga
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:141]: Biome superclass is: net.minecraft.world.biome.BiomeGenBase
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:142]: Biome implements these interfaces:
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:149]: Biome is not implementing any interface!
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:164]: Biome has correct superClass!
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:165]: BiomeGenBase superclass is: java.lang.Object
[14:57:45] [Server thread/INFO]: [sereneseasons.season.SeasonASMHelper:canBlockFreezeInSeason:172]: BiomeGenBase is not implementing any interface!
```

I made a little logging and it looks like it's not mixing correctly, Superclass of BiomeGenBase is `java.lang.Object` when it should be `BiomeMixin`

And I have no idea how Mixin works, to fix it.

**Comment by DarkShadow44** [comment]
> I made a little logging and it looks like it's not mixing correctly, Superclass of BiomeGenBase is java.lang.Object when it should be BiomeMixin

This is correct, the superclass of BiomeGenBase should be Object. Mixin mixes into the class, basically making the BiomeMixin disappear. But the missing interface is a problem yes.
Reson for that is:
`[12:37:54] [main/WARN]: Mixin config mixins.seasons.json requires mixin subsystem version 0.7 but 0.5.10 was found. The mixin config will not be applied.`

Some other mod is messing with Mixin, it uses an older version and that prevents SereneSeasons from working.
We need to find out which mod it is. You can do that by removing mods until it works, figuring out which mod/mods are causing the issue.

Are you using a modpack? If so, you can send me the link and I can help you. But I don't want to download all the mods you use individually...

**Comment by TekuSP** [comment]
Do you have Discord or any social platform? I don't want share modpack publicly.
You can write me if you have Discord on TekuSP#7658 or on telegram @TekuSP

**Comment by TekuSP** [comment]
ForgeEssentials Client was source of the issues.

**Comment by DarkShadow44** [comment]
FWIW, to make it work, open the "forge essentials client" mod and delete the "org" folder.
