### ISSUE TITLE
Dynamic Surroundings compatibility

### ISSUE THREAD

**Issue by ORANG4** [DarkShadow44/SereneSeasons#7]
Game crashes when I'm entering dimension with biomes that doesn't register in game properly (tropicraft, extraplanets and aether [dungeons dim]). This happens only when Dynamic Surroundings also installed.
In "Whitelisted Dimensions" there is only overworld.

`java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraftforge.common.BiomeDictionary.isBiomeRegistered(BiomeDictionary.java:267)
	at net.minecraftforge.common.BiomeDictionary.checkRegistration(BiomeDictionary.java:423)
	at net.minecraftforge.common.BiomeDictionary.isBiomeOfType(BiomeDictionary.java:250)
	at sereneseasons.config.BiomeConfig.usesTropicalSeasons(BiomeConfig.java:29)
	at sereneseasons.season.SeasonASMHelper.shouldAddRainParticles(SeasonASMHelper.java:257)
	at net.minecraft.world.biome.BiomeGenBase.func_76738_d(BiomeGenBase.java:747)
	at org.blockartistry.mod.DynSurround.data.BiomeRegistry$Entry.<init>(BiomeRegistry.java:108)
	at org.blockartistry.mod.DynSurround.data.BiomeRegistry.initialize(BiomeRegistry.java:210)
	at org.blockartistry.mod.DynSurround.data.BiomeRegistry.get(BiomeRegistry.java:240)
	at org.blockartistry.mod.DynSurround.data.BiomeRegistry.getSounds(BiomeRegistry.java:285)
	at org.blockartistry.mod.DynSurround.client.PlayerSoundEffectHandler.getBiomeSounds(PlayerSoundEffectHandler.java:72)
	at org.blockartistry.mod.DynSurround.client.PlayerSoundEffectHandler.process(PlayerSoundEffectHandler.java:107)
	at org.blockartistry.mod.DynSurround.client.ClientEffectHandler.clientTick(ClientEffectHandler.java:103)`

**Comment by ORANG4** [comment]
Possible fix:
In "SeasonASMHelper" in functions such as "shouldAddRainParticles" first check should be "isDimensionWhitelisted" and second "usesTropicalSeasons".
No crashes, works fine, hope for DragonAPI fix :)

**Comment by DarkShadow44** [comment]
Why close, is the issue no longer present?

**Comment by DarkShadow44** [comment]
Anyway, I pushed a fix.
